name: CI MacOS aarch64

on:
  # Trigger the workflow on push or pull request,
  #  but only for the master branch
  push:
    branches:
      - master
      - py313
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [ "3.13" ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate linux aarh64
        if: ${{ matrix.os == 'macos-latest' }}
        run: |          
          mkdir /tmp/acsylla
          cp -r . /tmp/acsylla
          docker run -v /tmp/acsylla:/io -e "PYTHON_VERSION=${{matrix.python-version}}" quay.io/pypa/manylinux_2_28_aarch64 /io/bin/build_manylinux_2_28_wheel.sh
          mkdir dist
          cp /tmp/acsylla/dist/acsylla-*.whl dist/
